apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-api
  namespace: sirius
spec:
  selector:
    matchLabels:
      app: myapp-api
  replicas: 5
  template:
    metadata:
      labels:
        app: myapp-api
    spec:
      containers:
        - name: appapi
          image: appapi:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: my-appapi-env
