apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-info
  namespace: sirius
spec:
  selector:
    matchLabels:
      app: myapp-info
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp-info
    spec:
      containers:
        - name: appinfo
          image: appinfo:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: my-appinfo-env

