apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-login
  namespace: sirius
spec:
  selector:
    matchLabels:
      app: myapp-login
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp-login
    spec:
      containers:
        - name: applogin
          image: applogin:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: my-applogin-env
